In [1]:
import pandas as pd

In [11]:
names = pd.read_csv("Pre-class Survey Survey Student Analysis Report.csv").iloc[:,[8,10]].columns
df = pd.read_csv("Pre-class Survey Survey Student Analysis Report.csv").iloc[:,[8,10]]
df.columns = ['set1','set2']
df, names

(                                                  set1  \
 0                                                  NaN
 1                                                  NaN
 2    it is a required course,meet my major requirem...
 3                                                  NaN
 4                                                  NaN
 ..                                                 ...
 162  it is a mandatory course for accounting major,...
 163  of major requirement,fulfil major requirement,...
 164  of major requirement ,fulfill major requiremen...
 165  I’m in acct major and it’s my required course ...
 166  ,,Econ,Acct,,It is because I am interested abo...

                                                   set2
 0                                                  NaN
 1                                                  NaN
 2                          2025,fashion retail,,,,,,,,
 3                                                  NaN
 4                                                  NaN
 ..                                                 ...
 162  2025,Marketing ,Marketing,,Hong Kong ,Influenc...
 163  2025 spring ,Audit firm,Audit firm,I didn’t pl...
 164  finish taking courses,audit firms,audit firms,...
 165  2025,Accounting firm\, own business ,No,Nutrit...
 166                          Next year\, 2025,,,,,,,,,

 [167 rows x 2 columns],
 Index(['785639: I am taking Advanced Managerial Accounting, because [one].\nI am taking Advanced Managerial Accounting in order to [two].\nWhat is your major? [three]\nIf you have a second major what is it? [four]\nIf you have a minor what is it? [five]\nWhy did you pick this major? [six]\nWhat grade do you want? [seven]\nWhat grade do you think you will get? [eight]\nDo you plan to take the CPA exam? [nine]\nDo you plan to take the CMA exam? [ten]\nIf so, where? (which country and system GAAP, IFRS, etc.) [eleven]', '785640: When do you plan to graduate? (i.e. finish taking courses) [one]\nWhat companies or businesses have you worked for? [two]\nIf you have a job lined up for next year, what company or business will you work for? [three]\nIf you plan to go to graduate school, what do you plan to study? [four]\nWhere do youwant to work next year? [five]\nWhat job do you want to do next year? [six]\nWhere do youwant to work in five years? [seven]\nWhat job do you want to do in five years? [eight]\nWhere do youwant to work in ten years? [nine]\nWhat job do you want to do in ten years? [ten]\n'], dtype='object'))

In [13]:
raw = df.dropna(how='all') #pd.read_csv("Pre-class Survey Survey Student Analysis Report.csv").dropna(how='all')
raw

,set1,set2
2,"it is a required course,meet my major requirem...","2025,fashion retail,,,,,,,,"
5,"thats a compulsory course (be honest :)),learn...","next year,education centre,Ecommerce,,,,,,,"
22,"of preregisteration,,Professional Accounting,I...",NaN
23,"it is compulsory ,graduate ,Accounting ,IS,,,,,,,",NaN
25,"required course for ACCT major,learn more abou...","2025,,,,,,,,,"
...,...,...
162,"it is a mandatory course for accounting major,...","2025,Marketing ,Marketing,,Hong Kong ,Influenc..."
163,"of major requirement,fulfil major requirement,...","2025 spring ,Audit firm,Audit firm,I didn’t pl..."
164,"of major requirement ,fulfill major requiremen...","finish taking courses,audit firms,audit firms,..."
165,I’m in acct major and it’s my required course ...,"2025,Accounting firm\, own business ,No,Nutrit..."
166,",,Econ,Acct,,It is because I am interested abo...","Next year\, 2025,,,,,,,,,"

In [67]:
# set1 = raw['set1'].str.split(',', expand=True)
set1 = df['set1'].str.split(r'(?<!\\),', expand=True)
# set2 = raw['set2'].str.split(',', expand=True)
set2 = df['set2'].str.split(r'(?<!\\),', expand=True)

In [68]:
set1 = set1.dropna(how='all').reset_index(drop=True).replace(r'\\,', ',', regex=True)
set1

,0,1,2,3,4,5,6,7,8,9,10
0,it is a required course,meet my major requirement,accounting,information system,no,,a range,b,no,no,
1,thats a compulsory course (be honest :)),learn more about accounting since i love accou...,OM,ACCT,,interest,A B range!,A B range,no currently,no currently,
2,of preregisteration,,Professional Accounting,Information Systems,N/A,,,,Yes,No,N/A
3,it is compulsory,graduate,Accounting,IS,,,,,,,
4,required course for ACCT major,learn more about the subject,ACCT,MARK,NA,Money,A+,A+,Maybe,Maybe,Hong Kong/ India
...,...,...,...,...,...,...,...,...,...,...,...
123,it is a mandatory course for accounting major,Know more about accounting,Accounting,Marketing,Psychological and behavioural science,Doing accounting is challenging yet rewarding,A,A,No,No,
124,of major requirement,fulfil major requirement,ACCT,OM,I don’t have a minor,I have performed excellent understanding towar...,A range,A range,Yes,Not yet,
125,of major requirement,fulfill major requirement,Acct,IS,NA,clear career path,A range,A-,Yes,No,
126,I’m in acct major and it’s my required course,Learn more about managerial accounting,Acct,No,PBS,Accounting is the one I’m malt interested in,A+!,A range hopefully,Considering,Considering,HK?
127,,,Econ,Acct,,It is because I am interested about it.,A range,B range or above,,,

In [69]:
set2 = set2.dropna(how='all').reset_index(drop=True).replace(r'\\,', ',', regex=True)
set2

,0,1,2,3,4,5,6,7,8,9
0,2025,fashion retail,,,,,,,,
1,next year,education centre,Ecommerce,,,,,,,
2,2025,,,,,,,,,
3,2025,,,,,,,,,
4,25,Assurance,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...
117,2025,Marketing,Marketing,,Hong Kong,Influencer marketing,Hong Kong,Influencer management,Artist management,South Korea
118,2025 spring,Audit firm,Audit firm,I didn’t plan to study graduate school yet,Hk,Audit,Hk,Not sure,Not sure,Not sure
119,finish taking courses,audit firms,audit firms,MBA,Audit firms,Auditing,Financial industry/gov department,Accountant,Didn’t plan,Didn’t plan
120,2025,"Accounting firm, own business",No,Nutrition actually…,Hk,Want to be an entrepreneur,Hk,Entrepreneur,Same,Same
121,"Next year, 2025",,,,,,,,,

In [70]:
set1[5].to_csv('whymajor.csv')

## questions
- I am taking Advanced Managerial Accounting, because [one].
- I am taking Advanced Managerial Accounting in order to [two].
- What is your major? [three]
- If you have a second major what is it? [four]
- If you have a minor what is it? [five]
- Why did you pick this major? [six]
- What grade do you want? [seven]
- What grade do you think you will get? [eight]
- Do you plan to take the CPA exam? [nine]
- Do you plan to take the CMA exam? [ten]
- If so, where? (which country and system GAAP, IFRS, etc.) [eleven]"

In [71]:
# question 1: I am taking managerial accounting because:
q1=set1[0].dropna()
set1['q1required']=set1[0].str.contains('requi|need|major|acc|grad')
set1['q1learn']=set1[0].str.contains('learn')
set1

,0,1,2,3,4,5,6,7,8,9,10,q1required,q1learn
0,it is a required course,meet my major requirement,accounting,information system,no,,a range,b,no,no,,True,False
1,thats a compulsory course (be honest :)),learn more about accounting since i love accou...,OM,ACCT,,interest,A B range!,A B range,no currently,no currently,,False,False
2,of preregisteration,,Professional Accounting,Information Systems,N/A,,,,Yes,No,N/A,False,False
3,it is compulsory,graduate,Accounting,IS,,,,,,,,False,False
4,required course for ACCT major,learn more about the subject,ACCT,MARK,NA,Money,A+,A+,Maybe,Maybe,Hong Kong/ India,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,it is a mandatory course for accounting major,Know more about accounting,Accounting,Marketing,Psychological and behavioural science,Doing accounting is challenging yet rewarding,A,A,No,No,,True,False
124,of major requirement,fulfil major requirement,ACCT,OM,I don’t have a minor,I have performed excellent understanding towar...,A range,A range,Yes,Not yet,,True,False
125,of major requirement,fulfill major requirement,Acct,IS,NA,clear career path,A range,A-,Yes,No,,True,False
126,I’m in acct major and it’s my required course,Learn more about managerial accounting,Acct,No,PBS,Accounting is the one I’m malt interested in,A+!,A range hopefully,Considering,Considering,HK?,True,False
127,,,Econ,Acct,,It is because I am interested about it.,A range,B range or above,,,,False,False

In [72]:
set1[0].describe()

count                         128
unique                        108
top       it is a required course
freq                            9
Name: 0, dtype: object

In [73]:
set1['q1required'].value_counts(normalize=True) * 100

q1required
True     78.125
False    21.875
Name: proportion, dtype: float64

In [74]:
set1['q1learn'].value_counts(normalize=True) * 100

q1learn
False    92.1875
True      7.8125
Name: proportion, dtype: float64

# Pre-class Survey

The following is analysis of last year's responses (since you still have time to fill our the survey).

# Question 1: 

## _"I am taking Advanced Managerial Accounting, because"_

- Most common answer: "It is a required course."
- 78\%: 'required', 'need', 'major', etc...
- 8\%: 'learn' (3 pp. higher than last year!)

In [75]:
set1[1].describe()

count          128
unique         100
top       graduate
freq            12
Name: 1, dtype: object

In [76]:
set1['q2required']=set1[1].str.contains('requi|need|major|acc|grad')
set1['q2required'].value_counts(normalize=True) * 100

q2required
True     63.28125
False    36.71875
Name: proportion, dtype: float64

In [77]:
set1['q2learn']=set1[1].str.contains('learn')
set1['q2learn'].value_counts(normalize=True) * 100

q2learn
False    75.0
True     25.0
Name: proportion, dtype: float64

# Question 2: 

## "I am taking Advanced Managerial Accounting in order to:"
- Most common answer is: "graduate" 
- 65%: 'required', 'need', 'major', etc...
- 25%: 'learn'

In [78]:
set1[5][131] #.dropna().value_counts().head(50)

KeyError: 131

In [80]:
# set1[6][131] #.dropna().value_counts().head(50)

In [81]:
set1['q2acct']=set1[2].str.contains('acc', case=False)
set1['q2acct'].value_counts(normalize=True)*100

q2acct
True     78.90625
False    21.09375
Name: proportion, dtype: float64

In [82]:
set1['q2fin']=set1[2].str.contains('fin', case=False)
set1['q2fin'].value_counts(normalize=True)*100

q2fin
False    92.1875
True      7.8125
Name: proportion, dtype: float64

## Question 3: What is your major?

- Accounting: 78\% (81\% 2024)
- Finance: 8\% (10\% 2024) 
- The rest: Econ, Marketing, IS, Operations, GBUS

In [83]:
set1['q5interest']=set1[5].str.contains('inte|like|enjo|use|chal|want',case=False)
set1['q5interest'].value_counts(normalize=True)*100

q5interest
False    51.5625
True     48.4375
Name: proportion, dtype: float64

In [84]:
set1['q5stabjob']=set1[5].str.contains('stab|job|career|work|prosp',case=False)
set1['q5stabjob'].value_counts(normalize=True)*100

q5stabjob
False    85.15625
True     14.84375
Name: proportion, dtype: float64

In [85]:
set1['q5intro']=set1[5].str.contains('introvert',case=False)
set1['q5intro'].value_counts()

q5intro
False    128
Name: count, dtype: int64

In [86]:
set1['q5love']=set1[5].str.contains('love',case=False) * 100 
set1['q5love'].value_counts(normalize=True) * 100

q5love
0      98.4375
100     1.5625
Name: proportion, dtype: float64

## Why did you pick this major?

- 50\% Interesting, enjoy, like, useful                                                                                              
- 16\% Stability/get job 

- 2\% __LOVE__ accounting! 

- "Because I am an introvert.", "No idea.", "I like math and money.", "I made a mistake in life."

- "I love accounting. When I solve some accounting problems I feel great."

In [87]:
set1[10].dropna().value_counts()

10
                                        42
Hong Kong                                9
HKICPA                                   9
IFRS                                     9
HK                                       5
N/A                                      5
HK IFRS                                  4
GAAP                                     4
Hong Kong, IFRS                          3
HK, IFRS                                 3
hk                                       3
gaap                                     2
Australia                                2
/                                        2
Hong Kong, QP                            1
HK CPA                                   1
hong kong ifrs                           1
hong kong                                1
not sure yet                             1
Hong Kong/ India                         1
Not sure yet                             1
HK QP                                    1
No                                       1
Hong Kong IFRS                           1
IFRS(?)                                  1
HK, China                                1
HKICP                                    1
no                                       1
NO                                       1
-                                        1
Gaap                                     1
NA                                       1
HK and IFRS                              1
n/a                                      1
Korea / Hong Kong - IFRS                 1
IFRS I guess                             1
I will take HKICPA QP program first!     1
I do not have the plan yet.              1
Canada                                   1
HK?                                      1
Name: count, dtype: int64

In [88]:
set1['q10hk']=set1[10].str.contains('hk|hong',case=False)
set1['q10hk'].value_counts()

q10hk
False    79
True     49
Name: count, dtype: int64

In [89]:
set1['q10ifrs']=set1[10].str.contains('ifrs',case=False)
set1['q10ifrs'].value_counts()

q10ifrs
False    103
True      25
Name: count, dtype: int64

In [90]:
set1['q10gaap']=set1[10].str.contains('gaap',case=False)
set1['q10gaap'].value_counts()

q10gaap
False    121
True       7
Name: count, dtype: int64

# Where/What system:
- 49 Hong Kong (2023: 54)
- 25 IFRS (2023: 17)
- 7 GAAP (2023:7)
- 1 Canada, India, Australia (2023: 1 UK, 0 India)

In [91]:
# set2['q4grad']=set1[3].str.contains('gaap',case=False)
# set1['q4grad'].value_counts()

In [92]:
set2[3].value_counts().head(10) # second major

3
           26
/           7
Finance     7
No          7
N/A         6
No plan     4
NA          3
MBA         3
UK          3
finance     2
Name: count, dtype: int64

In [93]:
set2[4].value_counts().head(10) # minor

4
Hong Kong     24
HK            13
              10
Hong Kong      8
hk             5
Hk             4
Big 4          4
hong kong      3
big 4          2
HSBC           2
Name: count, dtype: int64

In [94]:
set2[5].value_counts().head(10) # why

5
                      9
Audit                 5
banking               3
Accountant            3
Big4                  2
Accounting related    2
IT audit              2
Bank                  2
Actuary               1
accounting            1
Name: count, dtype: int64

In [95]:
set2[6].value_counts().head(10) # grade you want

6
Hong Kong     19
HK            12
              10
Hong Kong      6
hk             5
Hk             4
Big4           3
bank           3
Bank           2
Big 4          2
Name: count, dtype: int64

In [96]:
set2[7].value_counts().head(10) # grade get

7
                    13
Audit                6
Bank                 5
Banking              3
Accountant           3
-                    2
auditor              2
Business Analyst     2
Analyst              2
Accountant           2
Name: count, dtype: int64

In [97]:
set2[8].value_counts().head(10) # grade get

8
                      14
Bank                   3
Not sure               3
Banking                3
Accountant             2
not sure               2
Manager                2
Own business           2
Accounting related     2
Consultant             2
Name: count, dtype: int64

In [98]:
# set2[5].value_counts().head(50) # what do next year
set2['nextAudacc']=set2[7].str.contains('aud|acc|big|pwc|ass',case=False)
set2['nextAudacc'].value_counts()

nextAudacc
False    83
True     39
Name: count, dtype: int64

In [99]:
set2['nextbank']=set2[7].str.contains('bank',case=False)
set2['nextbank'].value_counts()

nextbank
False    104
True      18
Name: count, dtype: int64

In [100]:
set2['nextfinan']=set2[7].str.contains('finan|fund',case=False)
set2['nextfinan'].value_counts()

nextfinan
False    116
True       6
Name: count, dtype: int64

## What do you want to do next year?

- 39 (2023: 55) Accounting/Auditing/Big 4
- 24 (2023: 18) Banking
- 18 (2023: 10) Finance 
- 2 (2023: 10) Consulting

In [104]:
set2[5].value_counts() # [14].value_counts().head(50) # where next j

5
                                       9
Audit                                  5
banking                                3
Accountant                             3
Big4                                   2
                                      ..
Gain more experience in Controllers    1
Research Analyst in investment firm    1
Big 4/ bank                            1
Risk Assurance                         1
Want to be an entrepreneur             1
Name: count, Length: 102, dtype: int64

In [105]:
# set2[5].value_counts().head(50) # what do next year
set2['nextAudacc']=set2[7].str.contains('aud|acc|big|pwc|ass',case=False)
set2['nextAudacc'].value_counts()

nextAudacc
False    83
True     39
Name: count, dtype: int64

In [106]:
set2[7].value_counts().head(50) # what do next year
set2['nextbank']=set2[7].str.contains('bank',case=False)
set2['nextbank'].value_counts()

nextbank
False    104
True      18
Name: count, dtype: int64

In [107]:
set2['nextfinan']=set2[7].str.contains('finan|fund',case=False)
set2['nextfinan'].value_counts()

nextfinan
False    116
True       6
Name: count, dtype: int64

## What do you want to do next year?

- 55 Accounting/Auditing/Big 4
- 24 Banking
- 10 Consulting

## What about 10 years?

- Accounting, Banking, Consulting, Data Science.
- CEO, Venture Capital, Top luxury group, Founder.
- Inland Revenue Department, Hong Kong Government.
- Retired, working abroad (US, Singapore, UK, Indo., CA, UK).
- Traveling, farming, actor, singer/artist (viu.tv), Fire Department.
- __MYSTERY SHOPPER__

In [108]:
set2[9].value_counts()

9
Hong Kong                                18
                                         12
HK                                        8
Not sure                                  4
Australia                                 4
                                         ..
Self employed                             1
One of the Europe countries               1
/                                         1
KPMG/Commercial Firms/Investment Bank     1
Same                                      1
Name: count, Length: 69, dtype: int64

In [109]:
set2[8].value_counts()

8
                            14
Bank                         3
Not sure                     3
Banking                      3
Accountant                   2
                            ..
find enjoyable lifestyle     1
Financial manager            1
Managerial                   1
Portfolio Manager            1
Same                         1
Name: count, Length: 97, dtype: int64

In [110]:
set2[7].value_counts()

7
                                      13
Audit                                  6
Bank                                   5
Banking                                3
Accountant                             3
                                      ..
Travel around                          1
Accounting                             1
IT audit                               1
Financial or management onsultant      1
Entrepreneur                           1
Name: count, Length: 91, dtype: int64

In [111]:
set2[6].value_counts()

6
Hong Kong                             19
HK                                    12
                                      10
Hong Kong                              6
hk                                     5
                                      ..
Just want a job :(                     1
Australia                              1
Blackrock                              1
KPMG                                   1
Financial industry/gov department      1
Name: count, Length: 64, dtype: int64

In [112]:
set1

,0,1,2,3,4,5,6,7,8,9,...,q2learn,q2acct,q2fin,q5interest,q5stabjob,q5intro,q5love,q10hk,q10ifrs,q10gaap
0,it is a required course,meet my major requirement,accounting,information system,no,,a range,b,no,no,...,False,True,False,False,False,False,0,False,False,False
1,thats a compulsory course (be honest :)),learn more about accounting since i love accou...,OM,ACCT,,interest,A B range!,A B range,no currently,no currently,...,True,False,False,True,False,False,0,False,False,False
2,of preregisteration,,Professional Accounting,Information Systems,N/A,,,,Yes,No,...,False,True,False,False,False,False,0,False,False,False
3,it is compulsory,graduate,Accounting,IS,,,,,,,...,False,True,False,False,False,False,0,False,False,False
4,required course for ACCT major,learn more about the subject,ACCT,MARK,NA,Money,A+,A+,Maybe,Maybe,...,True,True,False,False,False,False,0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,it is a mandatory course for accounting major,Know more about accounting,Accounting,Marketing,Psychological and behavioural science,Doing accounting is challenging yet rewarding,A,A,No,No,...,False,True,False,True,False,False,0,False,False,False
124,of major requirement,fulfil major requirement,ACCT,OM,I don’t have a minor,I have performed excellent understanding towar...,A range,A range,Yes,Not yet,...,False,True,False,False,False,False,0,False,False,False
125,of major requirement,fulfill major requirement,Acct,IS,NA,clear career path,A range,A-,Yes,No,...,False,True,False,False,True,False,0,False,False,False
126,I’m in acct major and it’s my required course,Learn more about managerial accounting,Acct,No,PBS,Accounting is the one I’m malt interested in,A+!,A range hopefully,Considering,Considering,...,False,True,False,True,False,False,0,True,False,False
127,,,Econ,Acct,,It is because I am interested about it.,A range,B range or above,,,...,False,False,False,True,False,False,0,False,False,False

In [113]:
set2.tail(60)

,0,1,2,3,4,5,6,7,8,9,nextAudacc,nextbank,nextfinan
62,2025,Local accounting firms,Big4,Finance,Hong Kong,Big4,Big4,Audit,Banking,England,True,False,False
63,July 2025,MTR,,,Big 4,Audit associate,Investment Banks like JP Morgan,Accounting Analyst,,,True,False,False
64,Yes,EY BOC,N/A,UK,HK,Sales and Trading,HK,Sales and Trading,consulting or Sales and Trading,HK,False,False,False
65,After this semester,Audit firm,Commercial company,Communication,Hong Kong,Management trainee,Hong Kong,Manager in one of the commercial company,Have my own startup company,Hong Kong,False,False,False
66,year 2025,"accounting firm, company secretarial firm, wea...",Government,NA,Hong Kong,Government civil work,Hong Kong,Executive officer or Administrative Officer,Executive officer or Administrative Officer,Hong Kong,False,False,False
67,2025,/,PwC,information system,Hong Kong,Audit,not yet designed,Senior,Manager,not yet designed,False,False,False
68,Finish taking courses,,Insurance companies or bank companies,actuarial science,Bank,Actuary,Insurance companies,Actuary,Actuary,Insurance company,False,False,False
69,2025,kpmg,hsbc,management,bank,bank,bank,bank,bank,bank,False,True,False
70,2025 spring,"kpmg, lululemon",MTR,Sports Science,Financial,business analyst,hk,government officers,gov officer,HK,False,False,False
71,2025,local CPA firm and authority internship,Tech companies,N/A,Tech companies,Information system related internship,Big Four accounting firms,accounting related/analyst,management related,Authority,True,False,False
72,2024 Spring,"HSBC, KPMG",Deloitte,,hong kong,Tech Consulting,Canada,tech Consultant,Retire,Canada,False,False,False
73,2025,Cpa,Cpa,Finance,Hk,Financial analysts,Hk,Consultant,Consultant,Australia,False,False,False
74,2025,Finance and Audit firm,Banks,/,Hong Kong,Private Banking,Hong Kong,Start up in arts,Start up in arts,Hong Kong,False,False,False
75,Jun 2026,Hang Seng Bank,N/A,Accounting and Finance,I want to work at bank,Management trainee at bank,Large banking and financial services organisation,The job related to digital banking,The job related to digital banking,Large banking and financial services organisation,False,True,False
76,2025,"Majoris Group, MayerBrown",PwC,MBA,Internship in big 4,Auditing (Maybe?),Big 4,Audit,Haven’t really thought about it,Haven’t really thought about it,True,False,False
77,2025,intern in accounting and finance department in...,NA,NA,Big 4 or the accounting or finance department ...,accountant or auditor,Big 4 or the accounting or finance department ...,accountant or auditor,not sure,not sure,True,False,False
78,2025,NGO,Big 4,,PwC,Student Internship,Hong Kong,Accountant,Accountant,Hong Kong,True,False,False
79,June 2025,KPMG,Big4,PDGE,HK,Accounting related,HK,Accounting related,Accounting related,HK,True,False,False
80,2025,Big4,Conglomerate and Banking,Business,,,,,,,False,False,False
81,Spring 2025,"PwC, Wing On CPA & Associates","Big 4, Trading firms ,banks","UST, Wharton, LSE",Hong Kong,Don't know,Don't know,Don't know,Don't know,Don't know,False,False,False
82,2025 spring,"KPMG, PwC",No,No,HK,Audit,HK,Audit,Not sure,Not sure,True,False,False
83,2025,UST and an accounting firm,AIA,User research,Hong Kong,UI UX,Hong Kong,UI UX,UI UX,Remotely,False,False,False
84,2025 Spring,Accounting Firms,Big 4,Finance,Companies in Hong Kong,Accountant,Companies in Hong Kong,Auditor,Uncertain,Companies in Hong Kong,True,False,False
85,Finish taking courses,Local accounting firm,Government,Coding related subject,Government,Job with high stability,Job with high stability,Job with high stability,Job with high stability,Job with high stability,False,False,False
86,This semester,HSBC CICC,HSBC,No plan,HSBC,banking,HSBC,Banking,Banking,HSBC,False,True,False
87,2025,Accounting and private equity,Big4,No,Big4 accounting firms,External auditor,Hong Kong,Manager,Accounting related work,Hong Kong,False,False,False
88,2025,Big 4,Big 4,No,Big 4,External Auditor,Hong Kong,External Auditor,Accounting firm,Hong Kong,True,False,False
89,2024,KPMG,Auditing,UK,HK,accounting,HK,accounting,Accounting,HK,True,False,False
90,2025,None,Financial industry,I don't plan it yet,Hong Kong,Financial industry,"It does not matter to me, Hong Kong is fine",Financial industry,"I will see it after a few years, probably stil...",I didn't have that planning yet,False,False,True
91,2025,"KPMG, SHINEWING",Bank,Finance,Hong Kong,Bank,Hong Kong,Bank,Bank/start my own business,Hong Kong,False,True,False
92,"May, 2025",CSDC,NA,Information Systems,NA,NA,Hong Kong,Industry Research,Consultant,Hong Kong,False,False,False
93,finish taking courses,IT company,Gaming industry,Business,HK,BA,Mainland China,BA,Investment,Mainland China,False,False,False
94,2025,Deloitte,,,Outside HK haha,Banker,NYC,Still a banker,no idea as well,idk,False,True,False
95,2025,,,,Hong Kong,Financial or accounting related,Hong Kong,,,,False,False,False
96,2025,small-scale CPA Company,Big four accounting firms,Finance or Management,Accounting industry,Accounting Intern,Finance/Banking industry,Team leader in a financial firm or a bank,Civil servant,Government,False,True,True
97,2025,Bookstore manager,N/A,N/A,Hong Kong,Business related,Hong Kong,Business related,Business related / self employed,Hong Kong,False,False,False
98,Next year,Big 4 auditing firm,Banking,MSc Accounting,Hong Kong,Apply for postgraduate schools,To obtain a CPA license,Accounting or auditing,Banking,Hong Kong,True,False,False
99,may 2024,"EY, HKEX, family offices",Deloitte,PGDE,"PwC Consulting, Hospital Authority, Airport Au...","PwC Consulting, HA Finance Associate",Big 4/HKEX,Assistant manager of finance role,Senior Manager/Team Head of consultancy,Big 4/HKEX,True,False,True
100,2025,Financial institution,No,the US,Big 4,Auditor,-,-,-,-,False,False,False
101,2025,CPA Firm,Big 4,Finance,HK,Auditor,HK,Auditor Manager,Compliance/Financial Controller/Senior Audit M...,HK,True,False,False
102,next year,spotify,big 4,study for the cpa exam,Big 4,Big 4,IRD,IRD,Open a business by myself,Open a business by myself,False,False,False
103,2024 Jun,E-business,,,Hong Kong,Business Analyst,Hong Kong,Business Analyst,Animator,Hong Kong,False,False,False
104,2025,Deloitte Touche Tohmatsu and EQC Compliance Ad...,N/A,N/A,Consulting Firms,Consultant Intern,MBB (consulting firms),Management consultant,something I am really interested in,Companies in UK,False,False,False
105,finish taking courses,"4As, Big4, Custody, Insurance",Bank,/,HK,Bank,HK,Bank,Bank,HK,False,True,False
106,2025,Accounting firm,Big 4,No,Hong Kong,Accountant,Hong Kong,Accountant,Not yet plan,Not sure,True,False,False
107,Jul 2025,,,,,,,,,,False,False,False
108,2026,ibank or PE (value investing) or Family Office,UBS,Finance,UBS,Global Market,JPM,banking/consulting,RM and FM,blackrock,False,True,False
109,December 2025,Hang Seng Bank Limited,Banking and finance,Risk management,Yes,BNP student placement,Hong Kong,Banking and stable job,Banking and job with high salary,Australia,False,True,False
110,finish taking course,"audit, AM, insurance, corporate banking",n/a,finance,big 4,IT audit,bank,PB,PB,bank,False,False,False
111,2025 summer,Industrial Securities,any consulting company,finance,Hong Kong,consulting job,Hong Kong,auditing,consulting,Mainland China,True,False,False
112,Fall 2024,HSBC,N/A,Nursing,Hoping that I could get admitted to nursing sc...,Start with a new field of study,"Hospital, maybe",Being able to find my own purpose and joy of l...,I've got so much on hand that I could hardly h...,I don't plan that long,False,False,False
113,2025,"CCBA, HKMA",Banks or Regulators or Big4,No plan,Banks or Regulators,Compliance or Risk Management or Accounting,Banks or Regulators,Compliance or Risk Management or Accounting,Compliance or Risk Management or Accounting,Banks or Regulators,True,False,False
114,June 2025,KPMG,Bank,No plan,HK,Intern,Bank,Bank,Bank,Bank,False,True,False
115,2025,KPMG,Accounting,No plan,HK,PSSSIP,HK government,EO,EO,HK government,False,False,False
116,2025,CPA firm,Probably big4,Course related to accounting,Big4,Junior accountant/audit,Big4,Senior audit,Senior II,Big4,True,False,False
117,2025,Marketing,Marketing,,Hong Kong,Influencer marketing,Hong Kong,Influencer management,Artist management,South Korea,False,False,False
118,2025 spring,Audit firm,Audit firm,I didn’t plan to study graduate school yet,Hk,Audit,Hk,Not sure,Not sure,Not sure,False,False,False
119,finish taking courses,audit firms,audit firms,MBA,Audit firms,Auditing,Financial industry/gov department,Accountant,Didn’t plan,Didn’t plan,True,False,False
120,2025,"Accounting firm, own business",No,Nutrition actually…,Hk,Want to be an entrepreneur,Hk,Entrepreneur,Same,Same,False,False,False
121,"Next year, 2025",,,,,,,,,,False,False,False

In [115]:
set2.to_csv('hopesanddreams.csv')